"""CLI subcommands for dbread (bootstrap + help + extras management).

`dbread` (no args) starts the MCP stdio server. Subcommands:
  dbread init            -- scaffold ~/.dbread/{config.yaml, .env, sample.db}
                            + auto-install Claude Code skill when ~/.claude
                            is detected
  dbread install-skill   -- install / reinstall ~/.claude/skills/dbread/SKILL.md
  dbread add [name]      -- interactively add a new connection from a connection-string
  dbread add-extra <e>   -- install additional driver extras (preserves prior)
  dbread list-extras     -- show tracked vs importable extras
  dbread doctor          -- check config.yaml dialects vs installed drivers
  dbread --version       -- print package version
  dbread --help          -- print short help
"""

from __future__ import annotations

import os
import sqlite3
import sys
from importlib import resources
from pathlib import Path

from dbread.extras.installer import install_or_print
from dbread.extras.manager import (
    DIALECT_TO_EXTRA,
    EXTRA_TO_MODULE,
    bootstrap_state,
    detect_install_method,
    load_state,
    merge_extras,
    save_state,
    scan_installed_extras,
)


def _home_dir() -> Path:
    return Path.home() / ".dbread"


def _config_template(sample_db: Path) -> str:
    sqlite_url = f"sqlite:///file:{sample_db.as_posix()}?mode=ro&uri=true"
    return f"""\
# dbread config (generated by `dbread init`).
# Creds via `url_env` from ~/.dbread/.env — never commit real passwords.

connections:
  sample:
    url: {sqlite_url}
    dialect: sqlite
    rate_limit_per_min: 60
    statement_timeout_s: 10
    max_rows: 1000

  # --- Example: PostgreSQL. Uncomment, edit, add MYDB_URL=... to .env ---
  # mydb:
  #   url_env: MYDB_URL
  #   dialect: postgres
  #   rate_limit_per_min: 60
  #   statement_timeout_s: 30
  #   max_rows: 1000

audit:
  path: ~/.dbread/audit.jsonl
  rotate_mb: 50
  timezone: UTC              # IANA name; default UTC
  redact_literals: false     # true -> SQL literals masked to "?" in log
  retention_days: null       # e.g. 7 -> auto-prune entries older than 7 days

# Optional: cap total QPM across ALL connections (AND-ed with per-conn limit).
# Defends against rotation attacks. Leave commented for backward compat.
# global_rate_limit_per_min: 200
"""


_ENV_TEMPLATE = (
    "# dbread credentials (never commit).\n"
    "# Example: MYDB_URL=postgresql+psycopg2://ai_readonly:pw@host:5432/db\n"
)


def _seed_sample_db(path: Path) -> None:
    with sqlite3.connect(path) as con:
        con.executescript(
            """
            CREATE TABLE IF NOT EXISTS greetings (
                id INTEGER PRIMARY KEY,
                text TEXT NOT NULL
            );
            INSERT INTO greetings (text) VALUES
                ('hello from dbread'),
                ('v0.4 mongodb support'),
                ('try: SELECT * FROM greetings');
            """
        )
    if os.name != "nt":  # tighten perms on Unix; Windows uses attrib separately
        os.chmod(path, 0o444)


def _claude_skills_dir() -> Path:
    """Location Claude Code reads personal skills from."""
    return Path.home() / ".claude" / "skills"


def _bundled_skill_text() -> str:
    """Read the SKILL.md shipped inside the wheel (src/dbread/assets/skill.md)."""
    return resources.files("dbread.assets").joinpath("skill.md").read_text(encoding="utf-8")


def auto_refresh_skill() -> None:
    """Silently re-install the Claude Code skill when the bundled version
    differs from what's on disk. Called on every `dbread` invocation so
    `uv tool upgrade dbread` automatically refreshes the skill on next run.

    Skips silently if Claude Code isn't installed, or if the skill file
    doesn't exist (don't auto-create — user must run `dbread init` or
    `dbread install-skill` explicitly the first time).
    """
    try:
        target = _claude_skills_dir() / "dbread" / "SKILL.md"
        if not target.exists():
            return  # never auto-create; respect explicit opt-in
        bundled = _bundled_skill_text()
        if bundled == target.read_text(encoding="utf-8"):
            return  # already up to date
        target.write_text(bundled, encoding="utf-8")
        print(
            f"dbread: refreshed Claude Code skill at {target} "
            "(bundled version updated)",
            file=sys.stderr,
        )
    except Exception:  # noqa: BLE001 — never break CLI on skill refresh
        pass


def install_skill(*, force: bool = False, quiet: bool = False) -> int:
    """Install the Claude Code skill at ~/.claude/skills/dbread/SKILL.md.

    Idempotent: skips if the file exists and `force` is False. The user's
    `~/.claude` directory is required — we don't create it (that's owned
    by Claude Code itself) to avoid polluting the home dir.
    """
    claude_dir = Path.home() / ".claude"
    if not claude_dir.is_dir():
        if not quiet:
            print("skip     ~/.claude not found (install Claude Code first)")
        return 0

    target_dir = _claude_skills_dir() / "dbread"
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / "SKILL.md"

    if target.exists() and not force:
        if not quiet:
            print(f"skipped  {target} (already exists; use --force to reinstall)")
        return 0

    target.write_text(_bundled_skill_text(), encoding="utf-8")
    print(f"{'updated' if force else 'created'}  {target}")
    return 0


def init_config() -> int:
    """Scaffold ~/.dbread/ with a working SQLite demo. Idempotent.

    Also installs the Claude Code skill when ~/.claude is detected so the
    AI agent immediately knows the query workflow and error-handling rules.
    """
    home = _home_dir()
    home.mkdir(parents=True, exist_ok=True)
    cfg_path = home / "config.yaml"
    env_path = home / ".env"
    sample_db = home / "sample.db"

    created: list[str] = []
    skipped: list[str] = []

    if not sample_db.exists():
        _seed_sample_db(sample_db)
        created.append(str(sample_db))
    else:
        skipped.append(str(sample_db))

    if not cfg_path.exists():
        cfg_path.write_text(_config_template(sample_db), encoding="utf-8")
        created.append(str(cfg_path))
    else:
        skipped.append(str(cfg_path))

    if not env_path.exists():
        env_path.write_text(_ENV_TEMPLATE, encoding="utf-8")
        created.append(str(env_path))
    else:
        skipped.append(str(env_path))

    for p in created:
        print(f"created  {p}")
    for p in skipped:
        print(f"skipped  {p} (already exists)")

    # Opportunistic skill install — only when Claude Code is present.
    install_skill(quiet=True)

    print()
    print("Register with Claude Code:")
    print("  claude mcp add --scope user dbread \\")
    print(f"    --env DBREAD_CONFIG={cfg_path} \\")
    print("    -- dbread")
    return 0


def cmd_add_extra(args: list[str]) -> int:
    """`dbread add-extra <e1> [e2] ...` — install additional extras, preserving prior."""
    if not args:
        print("Usage: dbread add-extra <extra> [extra2 ...]")
        print(f"Available extras: {', '.join(sorted(EXTRA_TO_MODULE))}")
        return 2
    unknown = [e for e in args if e not in EXTRA_TO_MODULE]
    if unknown:
        print(f"Unknown extras: {', '.join(unknown)}")
        print(f"Available: {', '.join(sorted(EXTRA_TO_MODULE))}")
        return 2
    state = load_state() or bootstrap_state()
    new_union = merge_extras(state.extras, args)
    if new_union == state.extras:
        print(f"OK  already installed: {', '.join(state.extras)}")
        return 0
    ok = install_or_print(new_union, state.installed_via)
    if ok:
        from datetime import UTC, datetime
        state.extras = new_union
        state.updated_at = datetime.now(UTC).isoformat()
        save_state(state)
        print(f"OK  extras now: {', '.join(new_union)}")
        return 0
    return 3


def cmd_list_extras() -> int:
    """`dbread list-extras` — table of tracked vs importable."""
    state = load_state()
    actually = set(scan_installed_extras())
    tracked = set(state.extras) if state else set()
    all_extras = sorted(set(EXTRA_TO_MODULE) | tracked)
    install_method = state.installed_via if state else detect_install_method()
    print(f"Install method: {install_method}")
    state_status = "present" if state else "missing (will bootstrap on first add-extra)"
    print(f"State file:     {state_status}")
    print()
    print(f"{'EXTRA':<12} {'TRACKED':<9} {'IMPORTABLE'}")
    for e in all_extras:
        t = "yes" if e in tracked else "no"
        i = "yes" if e in actually else "no"
        print(f"{e:<12} {t:<9} {i}")
    return 0


def cmd_doctor() -> int:
    """`dbread doctor` — per-connection driver health check.

    Output is a one-glance table: each connection -> its dialect -> required
    driver extra -> import status (ok / MISSING / BROKEN). Verdict + fix at
    the bottom. Extras installed but unused by any connection are listed as
    a Note (not a warning) so users understand they're harmless.
    """
    cfg_path = os.environ.get("DBREAD_CONFIG")
    if not cfg_path:
        cfg_path = str(Path.home() / ".dbread" / "config.yaml")
    if not Path(cfg_path).exists():
        print(f"FAIL  No config file at {cfg_path}\n\nFix:\n  dbread init")
        return 3

    print(f"Config: {cfg_path}\n")

    try:
        from dbread.config import Settings  # noqa: PLC0415
        cfg = Settings.load(cfg_path)
    except Exception as e:  # noqa: BLE001 — surface config errors to user
        print(f"FAIL  Config invalid.\n\n  {e}\n\nFix:\n  Edit {cfg_path}")
        return 3

    have = set(scan_installed_extras())
    rows: list[tuple[str, str, str, str]] = []  # (conn, dialect, extra, status)
    missing_extras: list[str] = []
    broken: list[tuple[str, str]] = []  # (extra, error_first_line)

    import importlib  # noqa: PLC0415

    for name, conn in cfg.connections.items():
        extra = DIALECT_TO_EXTRA.get(conn.dialect)
        if extra is None:  # sqlite — stdlib, no extra needed
            rows.append((name, conn.dialect, "-", "ok (stdlib)"))
            continue
        if extra not in have:
            rows.append((name, conn.dialect, extra, "MISSING"))
            missing_extras.append(extra)
            continue
        # Deep-import check: catches broken-wheel cases (e.g. pyodbc with
        # missing system libodbc). find_spec succeeds, import_module raises.
        try:
            importlib.import_module(EXTRA_TO_MODULE[extra])
            rows.append((name, conn.dialect, extra, "ok"))
        except Exception as e:  # noqa: BLE001
            err = str(e).splitlines()[0][:60]
            rows.append((name, conn.dialect, extra, "BROKEN"))
            broken.append((extra, err))

    print(f"{'CONNECTION':<16} {'DIALECT':<11} {'EXTRA':<10} STATUS")
    for r in rows:
        print(f"{r[0]:<16} {r[1]:<11} {r[2]:<10} {r[3]}")
    print()

    needed_extras = {r[2] for r in rows if r[2] != "-"}
    unused = sorted(have - needed_extras)
    n_total = len(rows)
    n_bad = sum(1 for r in rows if r[3] in ("MISSING", "BROKEN"))

    if n_bad == 0:
        print(f"OK  {n_total} connection(s), all drivers present.")
        if unused:
            print(
                f"\nNote: extra(s) installed but unused by any connection: "
                f"{', '.join(unused)}"
            )
            print("      Safe to ignore (kept for future use).")
        return 0

    print(f"FAIL  {n_bad} of {n_total} connection(s) cannot connect.")
    if missing_extras:
        unique_missing = sorted(set(missing_extras))
        print(f"\nFix:\n  dbread add-extra {' '.join(unique_missing)}")
    if broken:
        print("\nBroken drivers (installed but unloadable — likely missing system lib):")
        for extra, err in broken:
            print(f"  {extra}: {err}")
    return 3


def cmd_add(args: list[str]) -> int:
    """`dbread add [name] [--from-stdin] [--no-test] [--manual] [--dialect-hint <x>]`"""
    name = None
    from_stdin = False
    no_test = False
    manual = False
    dialect_hint = None
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--from-stdin":
            from_stdin = True
        elif a == "--no-test":
            no_test = True
        elif a == "--manual":
            manual = True
        elif a == "--dialect-hint":
            i += 1
            if i >= len(args):
                print("--dialect-hint requires a value")
                return 2
            dialect_hint = args[i]
        elif a.startswith("--"):
            print(f"Unknown flag: {a}")
            return 2
        elif name is None:
            name = a
        else:
            print(f"Unexpected positional arg: {a}")
            return 2
        i += 1
    # Lazy import: avoid loading SQLAlchemy on every CLI invocation.
    from dbread.connstr.wizard import run_add_wizard
    return run_add_wizard(
        name, from_stdin=from_stdin, no_test=no_test, dialect_hint=dialect_hint, manual=manual
    )


_HELP = """\
dbread - read-only database MCP proxy for AI.

USAGE:
  dbread                         start the MCP stdio server (expects DBREAD_CONFIG)
  dbread init                    scaffold ~/.dbread/ + install Claude Code skill
  dbread install-skill [--force] install / reinstall ~/.claude/skills/dbread/SKILL.md
  dbread audit [opts]            analyze audit.jsonl (--since, --conn, --slow, --rejected, --tail)
  dbread add [name] [opts]       interactively add a new connection from a connection-string
                                 opts: --from-stdin, --no-test, --manual,
                                       --dialect-hint <pg|mysql|...>
  dbread add-extra <e1> ...      install additional driver extras (preserves prior)
  dbread list-extras             show tracked vs importable extras
  dbread doctor                  check config.yaml dialects vs installed drivers
  dbread --version               print version
  dbread --help                  print this help
"""


def print_help() -> int:
    sys.stdout.write(_HELP)
    return 0
