"""CLI subcommands for dbread (bootstrap + help).

`dbread` (no args) starts the MCP stdio server. Subcommands:
  dbread init            -- scaffold ~/.dbread/{config.yaml, .env, sample.db}
                            + auto-install Claude Code skill when ~/.claude
                            is detected
  dbread install-skill   -- install / reinstall ~/.claude/skills/dbread/SKILL.md
  dbread --version       -- print package version
  dbread --help          -- print short help
"""

from __future__ import annotations

import os
import sqlite3
import sys
from importlib import resources
from pathlib import Path


def _home_dir() -> Path:
    return Path.home() / ".dbread"


def _config_template(sample_db: Path) -> str:
    sqlite_url = f"sqlite:///file:{sample_db.as_posix()}?mode=ro&uri=true"
    return f"""\
# dbread config (generated by `dbread init`).
# Creds via `url_env` from ~/.dbread/.env — never commit real passwords.

connections:
  sample:
    url: {sqlite_url}
    dialect: sqlite
    rate_limit_per_min: 60
    statement_timeout_s: 10
    max_rows: 1000

  # --- Example: PostgreSQL. Uncomment, edit, add MYDB_URL=... to .env ---
  # mydb:
  #   url_env: MYDB_URL
  #   dialect: postgres
  #   rate_limit_per_min: 60
  #   statement_timeout_s: 30
  #   max_rows: 1000

audit:
  path: ~/.dbread/audit.jsonl
  rotate_mb: 50
  timezone: UTC              # IANA name; default UTC
  redact_literals: false     # true -> SQL literals masked to "?" in log
  retention_days: null       # e.g. 7 -> auto-prune entries older than 7 days

# Optional: cap total QPM across ALL connections (AND-ed with per-conn limit).
# Defends against rotation attacks. Leave commented for backward compat.
# global_rate_limit_per_min: 200
"""


_ENV_TEMPLATE = (
    "# dbread credentials (never commit).\n"
    "# Example: MYDB_URL=postgresql+psycopg2://ai_readonly:pw@host:5432/db\n"
)


def _seed_sample_db(path: Path) -> None:
    with sqlite3.connect(path) as con:
        con.executescript(
            """
            CREATE TABLE IF NOT EXISTS greetings (
                id INTEGER PRIMARY KEY,
                text TEXT NOT NULL
            );
            INSERT INTO greetings (text) VALUES
                ('hello from dbread'),
                ('v0.4 mongodb support'),
                ('try: SELECT * FROM greetings');
            """
        )
    if os.name != "nt":  # tighten perms on Unix; Windows uses attrib separately
        os.chmod(path, 0o444)


def _claude_skills_dir() -> Path:
    """Location Claude Code reads personal skills from."""
    return Path.home() / ".claude" / "skills"


def _bundled_skill_text() -> str:
    """Read the SKILL.md shipped inside the wheel (src/dbread/assets/skill.md)."""
    return resources.files("dbread.assets").joinpath("skill.md").read_text(encoding="utf-8")


def install_skill(*, force: bool = False, quiet: bool = False) -> int:
    """Install the Claude Code skill at ~/.claude/skills/dbread/SKILL.md.

    Idempotent: skips if the file exists and `force` is False. The user's
    `~/.claude` directory is required — we don't create it (that's owned
    by Claude Code itself) to avoid polluting the home dir.
    """
    claude_dir = Path.home() / ".claude"
    if not claude_dir.is_dir():
        if not quiet:
            print("skip     ~/.claude not found (install Claude Code first)")
        return 0

    target_dir = _claude_skills_dir() / "dbread"
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / "SKILL.md"

    if target.exists() and not force:
        if not quiet:
            print(f"skipped  {target} (already exists; use --force to reinstall)")
        return 0

    target.write_text(_bundled_skill_text(), encoding="utf-8")
    print(f"{'updated' if force else 'created'}  {target}")
    return 0


def init_config() -> int:
    """Scaffold ~/.dbread/ with a working SQLite demo. Idempotent.

    Also installs the Claude Code skill when ~/.claude is detected so the
    AI agent immediately knows the query workflow and error-handling rules.
    """
    home = _home_dir()
    home.mkdir(parents=True, exist_ok=True)
    cfg_path = home / "config.yaml"
    env_path = home / ".env"
    sample_db = home / "sample.db"

    created: list[str] = []
    skipped: list[str] = []

    if not sample_db.exists():
        _seed_sample_db(sample_db)
        created.append(str(sample_db))
    else:
        skipped.append(str(sample_db))

    if not cfg_path.exists():
        cfg_path.write_text(_config_template(sample_db), encoding="utf-8")
        created.append(str(cfg_path))
    else:
        skipped.append(str(cfg_path))

    if not env_path.exists():
        env_path.write_text(_ENV_TEMPLATE, encoding="utf-8")
        created.append(str(env_path))
    else:
        skipped.append(str(env_path))

    for p in created:
        print(f"created  {p}")
    for p in skipped:
        print(f"skipped  {p} (already exists)")

    # Opportunistic skill install — only when Claude Code is present.
    install_skill(quiet=True)

    print()
    print("Register with Claude Code:")
    print("  claude mcp add --scope user dbread \\")
    print(f"    --env DBREAD_CONFIG={cfg_path} \\")
    print("    -- dbread")
    return 0


_HELP = """\
dbread - read-only database MCP proxy for AI.

USAGE:
  dbread                         start the MCP stdio server (expects DBREAD_CONFIG)
  dbread init                    scaffold ~/.dbread/ + install Claude Code skill
  dbread install-skill [--force] install / reinstall ~/.claude/skills/dbread/SKILL.md
  dbread audit [opts]            analyze audit.jsonl (--since, --conn, --slow, --rejected, --tail)
  dbread --version               print version
  dbread --help                  print this help
"""


def print_help() -> int:
    sys.stdout.write(_HELP)
    return 0
